# Generated by Django 2.2 on 2020-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0002_auto_20200514_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestblood',
            name='date_of_donation',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
