# Generated by Django 2.2 on 2020-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0003_auto_20200514_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestblood',
            name='pin_code',
            field=models.IntegerField(help_text='You can edit your request later using this code', unique=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
